### ISSUE TITLE
Inhalt der E-Mail an Sigfox

### ISSUE THREAD

**Issue by polygamma** [polygamma/macio-sigfox-connection#4]
Verwendet wird der MKR FOX 1200, [endPacket](https://www.arduino.cc/en/Reference/SigFoxEndPacket) soll zurückliefern, ob Nachricht erfolgreich gesendet wurde, oder nicht.

Zurückgegeben wird der [Sigfox Status-Code](https://github.com/arduino-libraries/SigFox/blob/master/src/SigFox.cpp#L175), wie im [Atmel Datenblatt](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-9372-Smart-RF-ATA8520_Datasheet.pdf) beschrieben.

Der Statuscode liefert jedoch auch `0x00`, also "kein Fehler" zurück, wenn die Nachricht letztendlich nicht im Sigfox-Backend auftaucht. Gibt es eine Möglichkeit, dass der MKR FOX 1200 nicht komplett unbrauchbare Informationen über den Versand der Nachrichten liefert?

Die E-Mail sollte neben Sigfox auch an Atmel geschickt werden, da es deren Chip ist.

Weiterhin stellt sich die Frage, wie es mit einem Netzausbau in Kiel aussieht. Gibt es Pläne von Seiten Sigfox? Wie sieht es mit eigenem Repeater etc. aus? Zusammenfassend: Welche Möglichkeiten gibt es für macio, Sigfox in Kiel zu verwenden?

**Comment by polygamma** [comment]
Atmel: https://microchip.secure.force.com/CustomerCommunity/MySupport

**Comment by Belethil** [comment]
Hmm aber in dem verlinkten Issue/Pull Request steht ja nichts von _diesem_ problem, oder? 
Ich denke, auch wenn wir davon ausgehen dass es rein hardwareseitig ist sollten wir vielleicht dennoch einen issue bei Sigfox hinterlegen der die auf das return-problem bei endpacket anspricht (falls es den noch nicht gibt)

**Comment by polygamma** [comment]
Stimmt, spricht das Problem nur am Rande an. Sehe aber auch nicht, dass so eine Issue dort zielführend ist, weil die Library das Problem nicht fixen kann.

**Comment by Belethil** [comment]
Aye, aber die Hardware ist nicht auf GitHub, und zum einen wäre es ja interessant für andere Nutzer, zum anderen taucht das Problem ja bei Benutzung der library auf, es ist da ja also nicht völlig Fehl am Platz...  dunno, muss jetzt auch nicht sein, aber dachte so besteht die Möglichkeit dass andere Menschen ebenfalls Ideen zu nem Fix beitragen oder so :D

**Comment by Belethil** [comment]
Jedenfalls: Hier ist mal der first draft für den Mail-Text

Dear Sir or Madam,

I am part of a team of students at the University of Applied Sciences in Kiel, Germany. At the moment, we are working with Macio GmbH (https://www.macio.de/), a company in the IT sector, on a project to determine the capabilities and limits of the Sigfox IoT network.
While experimenting with Sigfox and the Arduino Mkrfox1200 Board, which uses a SAM-D21 chip provided by Atmel, we encountered several problems, most of which we were able to fix by making small improvements to the used libraries (in detail, those are the ArduinoLowPower, RTCZero and SigFox libraries for Arduino) and the USBCore of the board's kernel.
However, one problem we were not able to solve, as we believe it exists within the hardware itself. 

The problem appears when sending messages from the Arduino uC using the endPacket() function from the Sigfox library. This function, when used properly, will send a packet of data to the Sigfox backend. It will then return a status code, 
indicating if the message was successfully sent. The common understanding of "successfully sent" is assumed here as "successfully received by the Sigfox backend", as the return status would not be of any use otherwise. 
Sadly, this does not happen. For one, the Arduino documentation on the endPacket() function (found here https://www.arduino.cc/en/Reference/SigFoxEndPacket) is simply wrong (as can even be seen in the example directly below the explanation in the reference); apparently, a return value of 0 indicates "OK", while any other code would be an error. 
This also corresponds to the Atmel datasheet on their SAM-D21 chip, from where the endPacket() status code is retrieved from a status bit, which will also be 0 in case of success, with other values indicating an error. 
When using this corrected configuration (in contrast to the reference), sending messages is generally possible, and they will also be received in the Sigfox backend, if network coverage is sufficient. Still, one problem remains:
The return value of Sigfox.endPacket(), which is directly retrieved from the status bit on the chip, returns 0 whenever a message is *sent*, even if that message times out due to low/no network coverage or other factors and is never received anywhere.
This in turn not only makes it impossible to determine if a message was successfully sent to the Sigfox backend, it also provides us with not information whatsoever on what could have gone wrong at any given time. As the status bit is set by the hardware, we don't seem to be able to fix this on software side. 

The following links should provide you with more information on our findings (problems and solutions):
<LINKS EINFÜGEN>

Our first guess was that Sigfox and/or Atmel might not have a proper acknowledgement-system implemented in their network or on the chip, so there is no way to actually determine if a message has reached it's destination. However, we cannot determine the cause of the problem on our own, as we have no insight into the network's infrastructure. 
We believe that you would consider this an important matter, as proper error-handling is key to more sophisticated IoT-applications. Of course, we might well have overlooked something, so if you have any idea how to solve this problem on our side, we would be happy to hear it. 
Otherwise, we will gladly provide you with any additional information we can give to help fix this issue. In any way, we are looking forward to your feedback and to working with you on a solution. 

Best regards,

Kieran Murtagh

**Comment by null-git** [comment]
Klingt schon mal ganz gut.

In die E-Mail an Sigfox selbst sollte am Ende noch einen kurzen Absatz über deren weitere Netzausbaupläne in Norddeutschland / Kiel rein.

**Comment by polygamma** [comment]
> While experimenting with Sigfox and the Arduino Mkrfox1200 Board, which uses a SAM-D21 chip provided by Atmel

Der SAMD Chip ist eigentlich nicht relevant, der agiert ja nicht mit dem Netz. Das ATA8520 Modul ist dafür zuständig, wir zitieren ja auch aus dem Datenblatt.

> the used libraries (in detail, those are the ArduinoLowPower, RTCZero and SigFox libraries for Arduino) and the USBCore of the board's kernel.

Dort am besten direkt die libraries verlinken. Generell sehe ich aber nicht ganz, warum wir das in der E-Mail überhaupt ansprechen sollten, wenn es nichts mit dem aktuellen Anliegen zu tun hat, ich würde die Passage streichen.

> Sadly, this does not happen. For one, the Arduino documentation on the endPacket() function (found here https://www.arduino.cc/en/Reference/SigFoxEndPacket) is simply wrong (as can even be seen in the example directly below the explanation in the reference); 

Schlechte Argumentation, es könnte auch das Beispiel falsch sein und die Dokumentation richtig.

> This also corresponds to the Atmel datasheet on their SAM-D21 chip, from where the endPacket() 

Auch wieder - Was hat der SAMD Chip damit zu tun?

> retrieved from a status bit, which will also be 0 in case of success, with other values indicating an error.

Es ist kein Status bit, ein solches könnte nur 0 oder 1 zurückgeben, was nicht der Fall ist. Es sind "Status bytes".

> which is directly retrieved from the status bit on the chip, returns 0 whenever a message is sent

dasselbe

**Comment by Belethil** [comment]
askla :D ich hatte mir zugegebenermaßen den data sheet nicht angesehen, ich hab nur atmel chip in der doku gelesen und angenommen dass es um den gesamt chip geht - mache ich dann anders. Mit den status bytes auch, das war nur nicht drüber nachgedacht, dass 0x00 kein bit ist sollte mir eigentlich auch auffallen... den teil mit den libs kann man im prinzip auch rausnehmen, ich dachte es ist für die vielleicht ganz interessant, weil wir sonst garantiert egal wie toll unsere anfrage formuliert ist erstmal ein "habt ihr diese und jene library benutzt? Habt ihr es mal damit versucht? Habt ihr folgenden bekannten issue bedacht?" zurückbekommen weil tech-support immer davon ausgeht dass man dumm ist ... die sollen wissen, dass wir den fehler schon sehr klar identifiziert haben, war zumindest so mein gedanke

Und naja, wir wissen ja aber dass die Dokumentation falsch ist und das Beispiel richtig, was wir ja auch begründen mit dem status byte... insofern ist das ja keine argumentation, sondern einfach faktisch inkorrekt, oder sehe ich das falsch?

**Comment by polygamma** [comment]
Wenn wir das mit den libs ansprechen, sollte man (finde ich) auch ins Detail gehen. Wenn wir das nicht tun, ist es ziemlich unnütze Information für die. Also entweder komplett detailliert, was dann aber alles nichts mit unserem Anliegen zu tun hätte, oder es rauslassen, wobei ich für rauslassen wäre.

Alternativ einfach unser englisches PDF dranhängen mit Verweis, dass dort der Kram detailliert beschrieben ist.

> Und naja, wir wissen ja aber dass die Dokumentation falsch ist und das Beispiel richtig, was wir ja auch begründen mit dem status byte... insofern ist das ja keine argumentation, sondern einfach faktisch inkorrekt, oder sehe ich das falsch?

Der ganze Status byte Kram kommt erst später im Text, an der Stelle, so wie es dort jetzt steht, ist deine Argumentation: "Beispiel widerspricht Dokumentation, also ist Doku falsch", was offensichtlich logisch nicht gültig ist. Verweis einfach auf die Stellen im Sourcecode, wo man sieht, dass der status code vom chip all in all returned wird, denn das ist der Beweis, dass die Doku falsch ist.

**Comment by Belethil** [comment]
Hab den vorherigen kommentar geupdated (gibt ja ne history zum vergleichen), damit die kommentarsektion hier übersichtlich bleibt

**Comment by polygamma** [comment]
Bin damit in der Form einverstanden, kann abgeschickt werden von meiner Seite

**Comment by jakunar** [comment]
Ich hab die Mail gerade noch nicht ganz durch gelesen, sondern wollte gerade nochmal die Spces ansehen, ob es wriklich an der Hardware liegt oder eher eine Design-Frage war..
Bin bei der Suche gerade im Forum auf folgenden Thread gestoßen der letzteres zu bestätigen scheint.
https://ask.sigfox.com/questions/408/confirmation-of-uplink-messages.html

**Comment by vajaco** [comment]
Ich finde die Mail passt so. Selbst wenn es "working as intended" ist, wäre es gut das einmal von denen schwarz auf weiß zu haben, damit wir das an macio weitergeben können.

**Comment by jakunar** [comment]
Halte ich für überflüssig, aber ist kein Einspruch.
Gibt ne go von mir.

**Comment by null-git** [comment]
Kann meinetwegen auch so raus.

**Comment by polygamma** [comment]
Was ist nun mit der Netzabdeckung?

**Comment by Belethil** [comment]
Nanü, das mit der Netzabdeckung hatte ich sogar überlesen, bin aber von selbst drauf gekommen da nachzufragen :D und ja, ich habe die Nachricht am Freitag verschickt, bisher keine Antwort - sorry für die späte Antwort, stressiges "Wochenende"

**Comment by polygamma** [comment]
Wird niemals beantwortet werden.
